version: "3.9"

services:
  database_postgres:
    image: postgres
    container_name: postgresql
    restart: always
    ports:
      - 5432:5432
      # - 9229:9229
    environment:
      - POSTGRES_USER=johndoe
      - POSTGRES_PASSWORD=randompassword
      - POSTGRES_DB=mydb
    volumes:
      - pgdata:/data/postgres

  # app:
  #   build: .
  #   container_name: prisma
  #   ports:
  #     - 3333:3333
  #   volumes:
  #     - .:/usr/app
  #   links:
  #     - database_postgres
  #   depends_on:
  #     - database_postgres

volumes:
  pgdata:
    driver: local
